apiVersion: kubeadm.k8s.io/v1beta4
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    token: tokenid
    apiServerEndpoint: hostnamelb:6443
    caCertHashes:
      - "sha256:cahash"
  timeout: 5m0s
kind: JoinConfiguration
nodeRegistration:
  name: hostname
controlPlane:
  certificateKey: certkey